update_tournaments_smub_paris:
  cron: '0 2 * * */1'
  class: "UpdateTournamentsJob"
  queue: 'super_smash_bros_ultimate'
  args:
    - 'paris'
    - ''
    - 'super_smash_bros_ultimate'
update_tournaments_tekken7_paris:
  cron: '0 2 * * */1'
  class: "UpdateTournamentsJob"
  queue: 'tekken7'
  args:
    - 'paris'
    - ''
    - 'tekken7'
update_tournaments_dead_or_alive6_paris:
  cron: '0 2 * * */1'
  class: "UpdateTournamentsJob"
  queue: 'dead_or_alive6'
  args:
    - 'paris'
    - ''
    - 'dead_or_alive6'
update_tournaments_mortal_kombat11_paris:
  cron: '0 2 * * */1'
  class: "UpdateTournamentsJob"
  queue: 'mortal_kombat11'
  args:
    - 'paris'
    - ''
    - 'mortal_kombat11'